language: node_js
node_js:
- '6'
- '7'
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: sCKF9xz7XT2Sq0LoFNu9S9yhGK/Gyj7JnjOzHDVOwxr9ecgOKWba9a91JyDvqd02c4GQuy68GXQsOMzMeypHYASdvWU/l2BiSexQyleicDCMYxl2dNfOyfoLZDqEFgJQ2qYWw64X3k8XF35eXlXimFIH445GQuemDkO9U9brQgNnbPUuA5ABI+ZYE5YeycQ8JIiJxq7Sa1Vads5yFEWEpNBCwR8NWZFjkAB70h27q9ZG9QC8AXzkZYVI5bNW5/VYWf1LsWT5DcIrXHiOqWYQjWVp2XUgTBah0uzej0Wssl/uOGBA9C1XoTCJzcvozp7Mi5xoJ7Aa3fO2JJyuPz4JjZT9iOCXKfNMSUDBK1+vySEBjo6iQRfTY8CZ5tB5RoRZaHPUC/9dT91JwxHRzQ7VdSk1MlsiVx3jBwF8ZltaAokzTdXxiv3Embw3sGLNzuqaI9m0yOVvWDs3N/u0ggkQUD13VdxxWlzMHjChatL3UcNj+2lnh3KO7JBJaWIAkEeQTSPnp56HYnoo4ziMEBx9GbJD9c+DAOYs4sDcotnX1ij7ZAwRjDYIIw/qWPl0WovvRknKIiH5HTUK2KjFdNAMaq5IvFZt8RY2tuKc+RsycX+eQtHg+PaKxMk+CGbN/mEXpJvLzhfYYomkfz31ACSZ0QrAftTnb/Fl0Hp1vcrd2wQ=
