language: node_js
node_js:
- '6'
- '7'
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  api_key:
    secure: bHmQS3val3uthXnxsGXRBcCG5W8d20rL2oz5LFwP8OEn2aErR8SDvL7w1TISwZrZrnQ3v8zb4cw6p9j4iijRrheCZG4SBgvgBU4EnU2J7LQRYjidgzYh7mqqcIZrzTBvkjdiP/xQ5npnBsHUo1InRS/mgO5+UYdtMR/DVND3edral932UZ6aMmx/TX6QO1+DapJli7IFuYLOFyb1x77TwaReae4iMvzcB98HYs94wa4rIZS1TMK0iuNJegs8fvhn5ev2GfL2rHnboplUl33J+c0Efc7ts0snXH3jaRgPcoOwl6NTFghaAsqGe5lYA192vkcjBZhzMM947DEA2IYPrVyqv1vAi+4SGef9JI5YFp1lDksqrA6ppsMmKAjD1AVlS0/TuVGLK8nC/2x6tTPH4Xnz6Qdwc37OxpMXgmqUNmqfq9CXOVTYvAtkw7yrsaIRGUx/lR5uOElExwRwjJkOmL0fsom0AJ9ppzZzds9eID580IpK3Wg35mSR+AzKN3va/Oms3BG+8qjjGaFe83n9IixTgVmeSDypR460snEdHpV/u3ElQH0IQc+eGCOAtD0GGz3jfofeN81h79KCZbQ4xAH1tVWgM2MGbcj8/R5ntu9kETKSD85fIkctxaUo7ZeLHu5jAPYqb3fSyojEu09qkuZz4mYMbkCgDq0pYLmCiII=
